[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "UP4ROS"
authors = [{name = "Guglielmo Gemignani", email = "gemignani@magazino.eu"}]
dynamic = ["version", "description"]
