name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  up_commit: "master"
  up_tamer_commit: "master"
  up_pyperplan_commit: "master"
  up_fast_downward_commit: "master"

jobs:
  test_docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          - noetic

        include:
          # Noetic Ninjemys (May 2020 - May 2025)
          - docker_image: ubuntu:focal
            ros_distribution: noetic
            ros_version: 1

    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y wget python3-vcstool python3-pytest libfl-dev pip
      - name: Install unified planning from sources
        run: |
          mkdir src
          cd src
          git clone https://github.com/aiplan4eu/unified-planning.git
          cd unified-planning
          git checkout ${{env.up_commit}}
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r dev-requirements.txt
          python3 -m pip install tarski[arithmetic]
          # sudo apt install -y gringo
          python3 -m black --check --exclude=unified_planning/grpc/generated/ .
          python3 -m mypy unified_planning
          cd ..
          git clone https://github.com/aiplan4eu/up-tamer
          cd up-tamer
          git checkout ${{env.up_tamer_commit}}
          cd .. 
          python3 -m pip install up-tamer/
          git clone https://github.com/aiplan4eu/up-pyperplan
          cd up-pyperplan
          git checkout ${{env.up_pyperplan_commit}}
          cd ..
          python3 -m pip install up-pyperplan/
          cd unified-planning
          python3 setup.py install
          python3 scripts/test_imports.py
      - name: Build and test ROS 1
        id: build-and-test-ros-1
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: up4ros up_msgs
          target-ros1-distro: ${{ matrix.ros_distribution }}
      - name: Generate coverage
        run: |
          echo "Generating code coverage for up4ros"
          bash -c "source "$(find . -path "*install*" -type f -name "setup.bash" -print -quit)""
          cd $(find . -path "*src*" -type d -name "UP4ROS" -print -quit)
          python3 -m pytest up4ros --cov=up4ros --cov-report=xml
      - uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: false